### PR TITLE
Incorrect B instead of G key fix

### PR DESCRIPTION
**Pull request by MemBernd**
_Cmk-Curl B_ was active instead of _Cmk G_ on the standard Colemak Layout

### CODE REVIEW

**Comment by DreymaR** [comment]
Sorry, I don't understand what you're saying. That Curl(DH) is active, not just B vs G but the whole mod? Yes, it is. You can turn it off in PKL_Settings.ini. That should have nothing to do with the layouts themselves!

Am I missing something?

**Comment by MemBernd** [comment]
Should I close the pull request?

**Comment by DreymaR** [comment]
Ummm, okay. Thanks for picking up on that one! :-)

I'm obviously not experienced enough with all things GitHub, yet. ;-)

best, Øystein "DreymaR"

**Comment by DreymaR** [comment]
Oh, and try a fresh update now please.

And I'll try not to edit history... so much... ^_^

Ø

**Pull request closed without merging**
