### PR TITLE
Add stevep99's DpgH (D>P>G) mod-DH rotation

### PR DESCRIPTION
**Pull request by szabog**
The places, names of the remaps and remap cycle may be adjusted as seem fit. I've tried to follow the file's style.

**Image:** 
colemak_dpgh_keyb_ansi

**Note:** Right hand follows the standard DH mod.

### CODE REVIEW

**Comment by DreymaR** [comment]
Thank you! I think your suggestions were a little too thorough, but added the CurlDH_L_Dpg cycle and this remap:
`Cmk-Curl-DpgH   = ^CurlDH_L_Dpg , ^CurlDH_R_DHm ; The D>P>G rotation is a "poor man's DH" variant leaving the bottom row alone`
Anyone wishing another variant should edit the Remap file to get what they want. This is a secondary variant.

**Comment by szabog** [comment]
You're welcome.

I've seen you added it to `_eD_Remap.ini` in the latest commit -- thanks! Will it also work with the Wide ergo mod? If so, is the syntax `Cmk-Curl-DpgH_Wide_ANS`/`_ISO`?

**Comment by DreymaR** [comment]
The D>P>G version is only in the Remap file so anyone wishing to use it will have to find it there. My suggestion would be to simply edit this line:
`Cmk-Curl-DH     = ^CurlDH_L_Std , ^CurlDH_R_DHm` – replacing `Std` with `Dpg` (or renaming the lines instead)
That way, you can select any Curl variant and it'll use the DPG loop instead of standard DH. Help images would need updating of course.

Another way is to edit the remap in your layout.ini file, for instance turning `Cmk-CAW_@K` into `Cmk-CpAW_@K` and making a corresponding line in the Remap file or a Remaps section in the layout.ini file. But that's needlessly advanced for most.

**Comment by szabog** [comment]
All good.

**Pull request closed without merging**
